### PR TITLE
Talk a bit about security at the top

### PR DESCRIPTION
**Pull request by zmanian**

### CODE REVIEW

**Comment by ebuchman** [comment]
Thanks Zaki! Tho technically not true that they can only interact through ABI - ABI is a formatting standard for call-data that can be ignored if desired. Can you change the wording to reflect the more general potential for interoperability through call-data, with one particular standard being the ABI?

**Comment by zmanian** [comment]
See updated wording.

**Comment by ebuchman** [comment]
ah! I merged it and just added some changes of my own. See last commit!

**Comment by zmanian** [comment]
Typo in line 11. Otherwise LGTM

**Pull request closed without merging**
